core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('tasks/', include('testapp.urls')),
    path('admin/', admin.site.urls),
    
]

testapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('list', views.TaskListView.as_view(), name='task-list'),
]

testapp/models.py
from django.db import models

# Create your models here.

class Task(models.Model):
    title = models.CharField(max_length=100)
    completed = models.BooleanField(default=False, blank=True, null=True)

    def __str__(self):
        return self.title

testapp/views.py
from django.shortcuts import render

from . import models
# Create your views here.
from django.views.generic import ListView, TemplateView
from .models import Task


class HomePageView(TemplateView):
    model = Task
    template_name = 'home.html'

class TaskListView(ListView):
    model = Task
    template_name = 'task/list.html'
   

testapp/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>
  <body>

    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'home' %}">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'task-list' %}">Tasks</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link 1</a>
              </li>
              
              <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
              </li>
            </ul>
            
          </div>
        </div>
      </nav>

    <div class="container">
        {% block content %}{% endblock content %}
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

testapp/templates/home.html
{% extends 'base.html' %}

{% block content %}
    
    <h2>Welcome home</h2>
    <div id="chart">
    </div>
      
    <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
      
      <script>
        var options = {
          chart: {
            type: 'line'
          },
          series: [{
            name: 'sales',
            data: [30,40,35,50,49,60,70,91,125]
          }],
          xaxis: {
            categories: [1991,1992,1993,1994,1995,1996,1997, 1998,1999]
          }
        }
        
        var chart = new ApexCharts(document.querySelector("#chart"), options);
        
        chart.render();
      </script>
      
{% endblock content %}
    

testapp/templates/task/list.html
{% extends 'base.html' %}

{% block content %}
    
    <h2>Tasks</h2>
    <ul>
    {% for task in task_list %}
        <li>
            {{task.title}}
        </li>
    {% endfor %}    
    </ul>
    
{% endblock content %}
    